import { motion } from "framer-motion";
import {
  Wallet,
  ArrowUpRight,
  ArrowDownLeft,
  TrendingUp,
  ChevronRight,
  FileText,
  User,
  MapPin,
  Hash,
  CalendarDays,
  Briefcase,
  Printer,
  Globe,
} from "lucide-react";
import { useEffect, useState } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";

interface PropFirmAccount {
  id: string;
  propFirm: string;
  accountNumber: string;
  initialCost?: number;
  payoutHistory?: Array<{ date: string; amount: number }>;
  balance?: number;
  [key: string]: any;
}

interface TaxInfo {
  fullName: string;
  address: string;
  city: string;
  taxNumber: string;
  taxAdvisor: string;
  taxYear: string;
}

const TAX_STORAGE_KEY = "cw_tax_info";

interface CountryConfig {
  code: string;
  flag: string;
  name: string;
  currency: string;
  currencySymbol: string;
  currencyPosition: "before" | "after";
  locale: string;
  dateLocale: string;
  taxIdLabel: string;
  taxIdPlaceholder: string;
  taxAdvisorLabel: string;
  cityLabel: string;
  cityPlaceholder: string;
  streetPlaceholder: string;
  disclaimer: string;
}

const COUNTRIES: CountryConfig[] = [
  {
    code: "DE",
    flag: "🇩🇪",
    name: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    currencyPosition: "after",
    locale: "de-DE",
    dateLocale: "de-DE",
    taxIdLabel: "Tax Number (Steuernummer)",
    taxIdPlaceholder: "12/345/67890",
    taxAdvisorLabel: "Tax Advisor (Steuerberater)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "10115 Berlin",
    streetPlaceholder: "Musterstraße 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace professional tax advice (§ 4 StBerG). Please verify all figures with your Steuerberater.",
  },
  {
    code: "AT",
    flag: "🇦🇹",
    name: "Austria",
    currency: "EUR",
    currencySymbol: "€",
    currencyPosition: "after",
    locale: "de-AT",
    dateLocale: "de-AT",
    taxIdLabel: "Tax Number (Steuernummer)",
    taxIdPlaceholder: "12 345/6789",
    taxAdvisorLabel: "Tax Advisor (Steuerberater)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "1010 Wien",
    streetPlaceholder: "Musterstraße 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace professional tax advice. Please verify all figures with your Steuerberater.",
  },
  {
    code: "CH",
    flag: "🇨🇭",
    name: "Switzerland",
    currency: "CHF",
    currencySymbol: "CHF",
    currencyPosition: "before",
    locale: "de-CH",
    dateLocale: "de-CH",
    taxIdLabel: "Tax ID (AHV-Nummer / UID)",
    taxIdPlaceholder: "756.1234.5678.90",
    taxAdvisorLabel: "Tax Advisor (Treuhänder)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "8001 Zürich",
    streetPlaceholder: "Musterstrasse 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace professional tax advice. Please verify all figures with your Treuhänder.",
  },
  {
    code: "US",
    flag: "🇺🇸",
    name: "United States",
    currency: "USD",
    currencySymbol: "$",
    currencyPosition: "before",
    locale: "en-US",
    dateLocale: "en-US",
    taxIdLabel: "SSN / EIN",
    taxIdPlaceholder: "XXX-XX-XXXX",
    taxAdvisorLabel: "CPA / Tax Advisor",
    cityLabel: "City, State ZIP",
    cityPlaceholder: "New York, NY 10001",
    streetPlaceholder: "123 Main Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not constitute tax advice or replace consultation with a qualified CPA or tax professional.",
  },
  {
    code: "GB",
    flag: "🇬🇧",
    name: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    currencyPosition: "before",
    locale: "en-GB",
    dateLocale: "en-GB",
    taxIdLabel: "UTR / National Insurance No.",
    taxIdPlaceholder: "1234567890",
    taxAdvisorLabel: "Accountant / Tax Advisor",
    cityLabel: "City & Postcode",
    cityPlaceholder: "London, EC1A 1BB",
    streetPlaceholder: "12 Example Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace advice from a qualified accountant or HMRC guidance.",
  },
  {
    code: "NL",
    flag: "🇳🇱",
    name: "Netherlands",
    currency: "EUR",
    currencySymbol: "€",
    currencyPosition: "after",
    locale: "nl-NL",
    dateLocale: "nl-NL",
    taxIdLabel: "BSN / RSIN",
    taxIdPlaceholder: "123456789",
    taxAdvisorLabel: "Tax Advisor (Belastingadviseur)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "1234 AB Amsterdam",
    streetPlaceholder: "Voorbeeldstraat 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace advice from a qualified belastingadviseur.",
  },
  {
    code: "AU",
    flag: "🇦🇺",
    name: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    currencyPosition: "before",
    locale: "en-AU",
    dateLocale: "en-AU",
    taxIdLabel: "TFN / ABN",
    taxIdPlaceholder: "123 456 789",
    taxAdvisorLabel: "Tax Agent / Accountant",
    cityLabel: "City, State Postcode",
    cityPlaceholder: "Sydney NSW 2000",
    streetPlaceholder: "12 Example Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not constitute tax advice. Please consult a registered tax agent.",
  },
  {
    code: "CA",
    flag: "🇨🇦",
    name: "Canada",
    currency: "CAD",
    currencySymbol: "C$",
    currencyPosition: "before",
    locale: "en-CA",
    dateLocale: "en-CA",
    taxIdLabel: "SIN / Business Number",
    taxIdPlaceholder: "123 456 789",
    taxAdvisorLabel: "CPA / Tax Advisor",
    cityLabel: "City, Province Postal Code",
    cityPlaceholder: "Toronto, ON M5V 3A8",
    streetPlaceholder: "123 Main Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not constitute tax advice under the Income Tax Act. Please consult a qualified CPA.",
  },
];

const fmtCurrency = (n: number, country: CountryConfig) => {
  const formatted = n.toLocaleString(country.locale, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return country.currencyPosition === "before"
    ? `${country.currencySymbol}${formatted}`
    : `${formatted} ${country.currencySymbol}`;
};

const fmt = (n: number) =>
  n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function PropFirmSummary() {
  const [totalExpenses, setTotalExpenses] = useState(0);
  const [totalPayouts, setTotalPayouts] = useState(0);
  const [accountCount, setAccountCount] = useState(0);
  const [accounts, setAccounts] = useState<PropFirmAccount[]>([]);
  const [open, setOpen] = useState(false);
  const [countryCode, setCountryCode] = useState("US");
  const country = COUNTRIES.find((c) => c.code === countryCode) ?? COUNTRIES[3];
  const [taxInfo, setTaxInfo] = useState<TaxInfo>({
    fullName: "",
    address: "",
    city: "",
    taxNumber: "",
    taxAdvisor: "",
    taxYear: String(new Date().getFullYear()),
  });

  // Load tax info & country from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem(TAX_STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.countryCode) setCountryCode(parsed.countryCode);
        setTaxInfo(parsed);
      }
    } catch {}
  }, []);

  const updateCountry = (code: string) => {
    setCountryCode(code);
    const updated = { ...taxInfo, countryCode: code };
    localStorage.setItem(TAX_STORAGE_KEY, JSON.stringify(updated));
  };

  // Load prop firm accounts
  useEffect(() => {
    try {
      const accs: PropFirmAccount[] = JSON.parse(
        localStorage.getItem("cw_propfirm_accounts") || "[]"
      );
      let expenses = 0;
      let payouts = 0;
      accs.forEach((acc) => {
        if (acc.initialCost) expenses += acc.initialCost;
        if (acc.payoutHistory && Array.isArray(acc.payoutHistory)) {
          acc.payoutHistory.forEach((p) => { payouts += p.amount || 0; });
        }
      });
      setTotalExpenses(expenses);
      setTotalPayouts(payouts);
      setAccountCount(accs.length);
      setAccounts(accs);
    } catch (err) {
      console.error("Error loading prop firm accounts:", err);
    }
  }, []);

  const updateField = (field: keyof TaxInfo, value: string) => {
    const updated = { ...taxInfo, [field]: value };
    setTaxInfo(updated);
    localStorage.setItem(TAX_STORAGE_KEY, JSON.stringify({ ...updated, countryCode }));
  };

  const netProfit = totalPayouts - totalExpenses;
  const roi = totalExpenses > 0 ? ((netProfit / totalExpenses) * 100).toFixed(1) : "0";
  const isProfit = netProfit >= 0;

  const generateAndPrint = () => {
    const c = country;
    const dateStr = new Date().toLocaleDateString(c.dateLocale, { year: "numeric", month: "long", day: "numeric" });
    const fmtAmt = (n: number) => fmtCurrency(n, c);

    let accountRows = "";
    accounts.forEach((acc) => {
      const payoutsSum = (acc.payoutHistory || []).reduce(
        (s, p) => s + (p.amount || 0), 0
      );
      const net = payoutsSum - (acc.initialCost || 0);
      accountRows += `
        <tr>
          <td>${acc.propFirm}</td>
          <td>${acc.accountNumber}</td>
          <td class="num">- ${fmtAmt(acc.initialCost || 0)}</td>
          <td class="num pos">+ ${fmtAmt(payoutsSum)}</td>
          <td class="num ${net >= 0 ? "pos" : "neg"}">${net >= 0 ? "+" : ""}${fmtAmt(net)}</td>
        </tr>`;
    });

    let payoutRows = "";
    accounts.forEach((acc) => {
      (acc.payoutHistory || []).forEach((p) => {
        payoutRows += `
          <tr>
            <td>${acc.propFirm}</td>
            <td>${acc.accountNumber}</td>
            <td>${new Date(p.date).toLocaleDateString(c.dateLocale, { year: "numeric", month: "short", day: "numeric" })}</td>
            <td class="num pos">+ ${fmtAmt(p.amount || 0)}</td>
          </tr>`;
      });
    });

    if (!payoutRows) {
      payoutRows = `<tr><td colspan="4" style="text-align:center;color:#aaa;padding:16px">No payouts recorded</td></tr>`;
    }

    const positiveColor = isProfit ? "#3730a3" : "#c62828";
    const positiveBg = isProfit ? "#f0f0ff" : "#fff0f0";
    const positiveBorder = isProfit ? "#c8c0ff" : "#ffcccc";

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Tax Report ${taxInfo.taxYear} - ${taxInfo.fullName || "Trader"}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; color: #1a1a2e; background: #fff; }
    .page { max-width: 210mm; margin: 0 auto; padding: 18mm 20mm 14mm; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #7c3aed; padding-bottom: 14px; margin-bottom: 22px; }
    .logo { font-size: 20pt; font-weight: 800; color: #7c3aed; letter-spacing: -0.5px; }
    .logo span { color: #1a1a2e; }
    .doc-title { text-align: right; }
    .doc-title h1 { font-size: 15pt; font-weight: 700; color: #1a1a2e; }
    .doc-title p { font-size: 9pt; color: #666; margin-top: 3px; }
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 24px; }
    .meta-box { background: #f7f5ff; border: 1px solid #e0d6ff; border-radius: 8px; padding: 13px 15px; }
    .meta-box h3 { font-size: 7.5pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px; color: #7c3aed; margin-bottom: 9px; }
    .meta-row { display: flex; justify-content: space-between; font-size: 10pt; margin-bottom: 4px; gap: 8px; }
    .meta-row .lbl { color: #777; flex-shrink: 0; }
    .meta-row .val { font-weight: 600; color: #1a1a2e; text-align: right; }
    .summary { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 26px; }
    .sc { border-radius: 8px; padding: 13px 10px; text-align: center; }
    .sc.exp { background: #fff0f0; border: 1px solid #ffcccc; }
    .sc.pay { background: #f0faf0; border: 1px solid #b8edb8; }
    .sc.net { background: ${positiveBg}; border: 1px solid ${positiveBorder}; }
    .sc.roi { background: #fdf5ff; border: 1px solid #ddb8ff; }
    .sc .sc-lbl { font-size: 7.5pt; color: #777; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 5px; }
    .sc .sc-val { font-size: 13pt; font-weight: 800; }
    .sc.exp .sc-val { color: #c62828; }
    .sc.pay .sc-val { color: #2e7d32; }
    .sc.net .sc-val { color: ${positiveColor}; }
    .sc.roi .sc-val { color: #7c3aed; }
    section { margin-bottom: 26px; }
    section h2 { font-size: 11pt; font-weight: 700; color: #1a1a2e; margin-bottom: 10px; padding-left: 10px; border-left: 4px solid #7c3aed; }
    table { width: 100%; border-collapse: collapse; font-size: 9.5pt; }
    th { background: #7c3aed; color: #fff; padding: 8px 11px; text-align: left; font-weight: 600; font-size: 8.5pt; text-transform: uppercase; letter-spacing: 0.4px; }
    th.num, td.num { text-align: right; }
    td { padding: 8px 11px; border-bottom: 1px solid #eee; }
    tr:last-child td { border-bottom: none; }
    tr:nth-child(even) td { background: #fafafa; }
    .pos { color: #2e7d32; font-weight: 600; }
    .neg { color: #c62828; font-weight: 600; }
    .total-row td { font-weight: 700; background: #f0eeff !important; border-top: 2px solid #7c3aed; }
    .footer { margin-top: 28px; padding-top: 12px; border-top: 1px solid #e0e0e0; display: flex; justify-content: space-between; font-size: 7.5pt; color: #aaa; }
    .disclaimer { font-size: 8pt; color: #bbb; margin-top: 8px; font-style: italic; line-height: 1.5; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .page { padding: 10mm 15mm; }
    }
  </style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="logo">Cycle<span>Wise</span></div>
    <div class="doc-title">
      <h1>Tax Report - Prop Firm Trading</h1>
      <p>Tax Year ${taxInfo.taxYear} &nbsp;&#183;&nbsp; Created on ${dateStr}</p>
    </div>
  </div>

  <div class="meta-grid">
    <div class="meta-box">
      <h3>Taxpayer</h3>
      <div class="meta-row"><span class="lbl">Name</span><span class="val">${taxInfo.fullName || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">Address</span><span class="val">${taxInfo.address || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">${c.cityLabel}</span><span class="val">${taxInfo.city || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">${c.taxIdLabel}</span><span class="val">${taxInfo.taxNumber || "&#8211;"}</span></div>
    </div>
    <div class="meta-box">
      <h3>Document Information</h3>
      <div class="meta-row"><span class="lbl">Tax Year</span><span class="val">${taxInfo.taxYear}</span></div>
      <div class="meta-row"><span class="lbl">Country</span><span class="val">${c.flag} ${c.name}</span></div>
      <div class="meta-row"><span class="lbl">${c.taxAdvisorLabel}</span><span class="val">${taxInfo.taxAdvisor || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">No. of Accounts</span><span class="val">${accountCount}</span></div>
    </div>
  </div>

  <div class="summary">
    <div class="sc exp">
      <div class="sc-lbl">Business Expenses</div>
      <div class="sc-val">- ${fmtAmt(totalExpenses)}</div>
    </div>
    <div class="sc pay">
      <div class="sc-lbl">Income (Payouts)</div>
      <div class="sc-val">+ ${fmtAmt(totalPayouts)}</div>
    </div>
    <div class="sc net">
      <div class="sc-lbl">Net Profit / Loss</div>
      <div class="sc-val">${isProfit ? "+" : ""}${fmtAmt(netProfit)}</div>
    </div>
    <div class="sc roi">
      <div class="sc-lbl">Return on Investment</div>
      <div class="sc-val">${roi} %</div>
    </div>
  </div>

  <section>
    <h2>Account Overview</h2>
    <table>
      <thead>
        <tr>
          <th>Prop Firm</th>
          <th>Account Number</th>
          <th class="num">Expenses</th>
          <th class="num">Income</th>
          <th class="num">Result</th>
        </tr>
      </thead>
      <tbody>
        ${accountRows || '<tr><td colspan="5" style="text-align:center;color:#aaa;padding:16px">No accounts recorded</td></tr>'}
        <tr class="total-row">
          <td colspan="2">Total</td>
          <td class="num neg">- ${fmtAmt(totalExpenses)}</td>
          <td class="num pos">+ ${fmtAmt(totalPayouts)}</td>
          <td class="num ${isProfit ? "pos" : "neg"}">${isProfit ? "+" : ""}${fmtAmt(netProfit)}</td>
        </tr>
      </tbody>
    </table>
  </section>

  <section>
    <h2>Payout History</h2>
    <table>
      <thead>
        <tr>
          <th>Prop Firm</th>
          <th>Account Number</th>
          <th>Date</th>
          <th class="num">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${payoutRows}
      </tbody>
    </table>
  </section>

  <div class="footer">
    <span>&#169; ${new Date().getFullYear()} CycleWise &nbsp;&#183;&nbsp; ${taxInfo.fullName || "Trader"}</span>
    <span>Tax Year ${taxInfo.taxYear}</span>
  </div>
  <p class="disclaimer">
    ${c.disclaimer}
  </p>
</div>
</body>
</html>`;

    const newWin = window.open("", "_blank");
    if (newWin) {
      newWin.document.write(html);
      newWin.document.close();
      setTimeout(() => newWin.print(), 600);
    }
  };

  return (
    <>
      {/* Clickable Summary Card */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        onClick={() => setOpen(true)}
        className="cursor-pointer rounded-2xl bg-gradient-to-br from-secondary/50 to-accent/30 p-5 transition-all hover:ring-2 hover:ring-primary/40 hover:shadow-lg"
      >
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-card p-2.5">
              <Wallet className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h3 className="font-semibold text-foreground">Prop Firm Summary</h3>
              <p className="text-xs text-muted-foreground">
                {accountCount} {accountCount === 1 ? "account" : "accounts"} · Create tax report
              </p>
            </div>
          </div>
          <div className="flex items-center gap-1 rounded-lg bg-card/70 px-2.5 py-1.5">
            <FileText className="h-3.5 w-3.5 text-primary" />
            <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />
          </div>
        </div>

        <div className="mt-4 grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <ArrowDownLeft className="h-3 w-3" />
              Expenses
            </div>
            <p className="text-lg font-semibold text-foreground tabular-nums">
              ${totalExpenses.toLocaleString()}
            </p>
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <ArrowUpRight className="h-3 w-3" />
              Payouts
            </div>
            <p className="text-lg font-semibold text-foreground tabular-nums">
              ${totalPayouts.toLocaleString()}
            </p>
          </div>
        </div>

        <div className="mt-4 rounded-xl bg-card/60 p-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Net Profit</p>
              <p
                className={`text-2xl font-bold tabular-nums ${
                  isProfit ? "text-accent-foreground" : "text-destructive"
                }`}
              >
                {isProfit ? "+" : "-"}${Math.abs(netProfit).toLocaleString()}
              </p>
            </div>
            <div
              className={`flex items-center gap-1 rounded-lg px-3 py-1.5 tabular-nums ${
                isProfit
                  ? "bg-accent/50 text-accent-foreground"
                  : "bg-destructive/10 text-destructive"
              }`}
            >
              <TrendingUp className="h-4 w-4" />
              <span className="text-sm font-semibold">{roi}% ROI</span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Tax Report Dialog */}
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] flex flex-col gap-0 p-0">
          <DialogHeader className="px-6 pt-6 pb-4 border-b border-border">
            <div className="flex items-center gap-3">
              <div className="rounded-xl bg-primary/10 p-2.5">
                <FileText className="h-5 w-5 text-primary" />
              </div>
              <div>
                <DialogTitle className="text-lg font-semibold">
                  Create Tax Report
                </DialogTitle>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Professional document for your tax advisor
                </p>
              </div>
            </div>
          </DialogHeader>

          <Tabs defaultValue="data" className="flex flex-col flex-1 min-h-0">
            <TabsList className="mx-6 mt-4 mb-0 grid grid-cols-2">
              <TabsTrigger value="data" className="gap-2">
                <User className="h-3.5 w-3.5" />
                My Details
              </TabsTrigger>
              <TabsTrigger value="preview" className="gap-2">
                <FileText className="h-3.5 w-3.5" />
                Preview
              </TabsTrigger>
            </TabsList>

            {/* TAB: Personal Data */}
            <TabsContent value="data" className="overflow-auto px-6 pb-2 mt-0">
              <p className="text-xs text-muted-foreground mt-4 mb-5">
                These details appear in the tax report and are saved locally.
              </p>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <Label className="flex items-center gap-1.5 text-sm">
                    <Globe className="h-3.5 w-3.5 text-muted-foreground" />
                    Country
                  </Label>
                  <Select value={countryCode} onValueChange={updateCountry}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {COUNTRIES.map((c) => (
                        <SelectItem key={c.code} value={c.code}>
                          <span className="flex items-center gap-2">
                            <span>{c.flag}</span>
                            <span>{c.name}</span>
                            <span className="text-muted-foreground text-xs">({c.currency})</span>
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1.5">
                  <Label className="flex items-center gap-1.5 text-sm">
                    <User className="h-3.5 w-3.5 text-muted-foreground" />
                    Full Name
                  </Label>
                  <Input
                    placeholder="John Smith"
                    value={taxInfo.fullName}
                    onChange={(e) => updateField("fullName", e.target.value)}
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="flex items-center gap-1.5 text-sm">
                      <MapPin className="h-3.5 w-3.5 text-muted-foreground" />
                      Street &amp; Number
                    </Label>
                    <Input
                      placeholder={country.streetPlaceholder}
                      value={taxInfo.address}
                      onChange={(e) => updateField("address", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-sm">{country.cityLabel}</Label>
                    <Input
                      placeholder={country.cityPlaceholder}
                      value={taxInfo.city}
                      onChange={(e) => updateField("city", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="flex items-center gap-1.5 text-sm">
                      <Hash className="h-3.5 w-3.5 text-muted-foreground" />
                      {country.taxIdLabel}
                    </Label>
                    <Input
                      placeholder={country.taxIdPlaceholder}
                      value={taxInfo.taxNumber}
                      onChange={(e) => updateField("taxNumber", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="flex items-center gap-1.5 text-sm">
                      <CalendarDays className="h-3.5 w-3.5 text-muted-foreground" />
                      Tax Year
                    </Label>
                    <Input
                      placeholder="2025"
                      value={taxInfo.taxYear}
                      onChange={(e) => updateField("taxYear", e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <Label className="flex items-center gap-1.5 text-sm">
                    <Briefcase className="h-3.5 w-3.5 text-muted-foreground" />
                    {country.taxAdvisorLabel} (optional)
                  </Label>
                  <Input
                    placeholder={`e.g. Smith & Partners`}
                    value={taxInfo.taxAdvisor}
                    onChange={(e) => updateField("taxAdvisor", e.target.value)}
                  />
                </div>

                <Separator />

                <div className="rounded-xl bg-muted/50 p-4">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-3">
                    Financial Summary in Report
                  </p>
                  <div className="grid grid-cols-3 gap-3">
                    <div className="rounded-lg bg-destructive/10 p-3 text-center">
                      <p className="text-[10px] text-muted-foreground mb-1">Expenses</p>
                      <p className="font-bold text-destructive tabular-nums text-sm">
                        - {fmtCurrency(totalExpenses, country)}
                      </p>
                    </div>
                    <div className="rounded-lg bg-green-500/10 p-3 text-center">
                      <p className="text-[10px] text-muted-foreground mb-1">Income</p>
                      <p className="font-bold text-green-600 tabular-nums text-sm">
                        + {fmtCurrency(totalPayouts, country)}
                      </p>
                    </div>
                    <div
                      className={`rounded-lg p-3 text-center ${
                        isProfit ? "bg-primary/10" : "bg-destructive/10"
                      }`}
                    >
                      <p className="text-[10px] text-muted-foreground mb-1">Net</p>
                      <p
                        className={`font-bold tabular-nums text-sm ${
                          isProfit ? "text-primary" : "text-destructive"
                        }`}
                      >
                        {isProfit ? "+" : ""}{fmtCurrency(netProfit, country)}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </TabsContent>

            {/* TAB: Preview */}
            <TabsContent value="preview" className="min-h-0 px-6 pb-2 mt-0">
              <ScrollArea className="h-[400px] mt-4 rounded-xl border border-border">
                <div className="p-5 space-y-4 font-sans text-sm">
                  {/* Preview Header */}
                  <div className="flex items-start justify-between border-b-2 border-primary pb-4">
                    <div>
                      <span className="text-xl font-black text-primary">Cycle</span>
                      <span className="text-xl font-black text-foreground">Wise</span>
                    </div>
                    <div className="text-right">
                      <p className="font-bold text-base">Tax Report – Prop Firm Trading</p>
                      <p className="text-xs text-muted-foreground">
                        Tax Year {taxInfo.taxYear} · Created on{" "}
                        {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
                      </p>
                    </div>
                  </div>

                  {/* Person + Meta */}
                  <div className="grid grid-cols-2 gap-3">
                    {[
                      {
                        title: "Taxpayer",
                        rows: [
                          ["Name", taxInfo.fullName || "–"],
                          ["Address", taxInfo.address || "–"],
                          [country.cityLabel, taxInfo.city || "–"],
                          [country.taxIdLabel, taxInfo.taxNumber || "–"],
                        ],
                      },
                      {
                        title: "Document Information",
                        rows: [
                          ["Tax Year", taxInfo.taxYear],
                          ["Country", `${country.flag} ${country.name}`],
                          [country.taxAdvisorLabel, taxInfo.taxAdvisor || "–"],
                          ["No. of Accounts", String(accountCount)],
                        ],
                      },
                    ].map((box) => (
                      <div
                        key={box.title}
                        className="rounded-lg bg-primary/5 border border-primary/20 p-3 space-y-1.5"
                      >
                        <p className="text-[9px] font-bold uppercase tracking-wider text-primary mb-2">
                          {box.title}
                        </p>
                        {box.rows.map(([label, value]) => (
                          <div key={label} className="flex justify-between text-xs gap-2">
                            <span className="text-muted-foreground">{label}</span>
                            <span className="font-semibold text-right">{value}</span>
                          </div>
                        ))}
                      </div>
                    ))}
                  </div>

                  {/* Summary boxes */}
                  <div className="grid grid-cols-4 gap-2">
                    {[
                      {
                        label: "Expenses",
                        value: `- ${fmtCurrency(totalExpenses, country)}`,
                        color: "text-destructive",
                        bg: "bg-destructive/10",
                      },
                      {
                        label: "Income",
                        value: `+ ${fmtCurrency(totalPayouts, country)}`,
                        color: "text-green-600",
                        bg: "bg-green-500/10",
                      },
                      {
                        label: "Net Profit",
                        value: `${isProfit ? "+" : ""}${fmtCurrency(netProfit, country)}`,
                        color: isProfit ? "text-primary" : "text-destructive",
                        bg: isProfit ? "bg-primary/10" : "bg-destructive/10",
                      },
                      {
                        label: "ROI",
                        value: `${roi} %`,
                        color: "text-purple-500",
                        bg: "bg-purple-500/10",
                      },
                    ].map((item) => (
                      <div
                        key={item.label}
                        className={`rounded-lg ${item.bg} p-2.5 text-center`}
                      >
                        <p className="text-[9px] text-muted-foreground uppercase mb-1">
                          {item.label}
                        </p>
                        <p className={`text-xs font-black ${item.color} tabular-nums`}>
                          {item.value}
                        </p>
                      </div>
                    ))}
                  </div>

                  {/* Accounts table */}
                  <div>
                    <p className="text-xs font-bold pl-2 border-l-2 border-primary mb-2">
                      Account Overview
                    </p>
                    <table className="w-full text-xs border-collapse">
                      <thead>
                        <tr className="bg-primary text-primary-foreground">
                          {["Prop Firm", "Account No.", "Expenses", "Income", "Result"].map(
                            (h) => (
                              <th
                                key={h}
                                className="px-2.5 py-1.5 text-left font-semibold text-[10px]"
                              >
                                {h}
                              </th>
                            )
                          )}
                        </tr>
                      </thead>
                      <tbody>
                        {accounts.length === 0 ? (
                          <tr>
                            <td
                              colSpan={5}
                              className="text-center text-muted-foreground py-3 text-xs"
                            >
                              No accounts recorded
                            </td>
                          </tr>
                        ) : (
                          accounts.map((acc) => {
                            const ps = (acc.payoutHistory || []).reduce(
                              (s, p) => s + (p.amount || 0),
                              0
                            );
                            const n = ps - (acc.initialCost || 0);
                            return (
                              <tr
                                key={acc.id}
                                className="border-b border-border even:bg-muted/30"
                              >
                                <td className="px-2.5 py-1.5">{acc.propFirm}</td>
                                <td className="px-2.5 py-1.5">{acc.accountNumber}</td>
                                <td className="px-2.5 py-1.5 text-right text-destructive">
                                  - {fmtCurrency(acc.initialCost || 0, country)}
                                </td>
                                <td className="px-2.5 py-1.5 text-right text-green-600">
                                  + {fmtCurrency(ps, country)}
                                </td>
                                <td
                                  className={`px-2.5 py-1.5 text-right font-semibold ${
                                    n >= 0 ? "text-primary" : "text-destructive"
                                  }`}
                                >
                                  {n >= 0 ? "+" : ""}{fmtCurrency(n, country)}
                                </td>
                              </tr>
                            );
                          })
                        )}
                        <tr className="bg-primary/10 font-bold border-t-2 border-primary">
                          <td colSpan={2} className="px-2.5 py-1.5">
                            Total
                          </td>
                          <td className="px-2.5 py-1.5 text-right text-destructive">
                            - {fmtCurrency(totalExpenses, country)}
                          </td>
                          <td className="px-2.5 py-1.5 text-right text-green-600">
                            + {fmtCurrency(totalPayouts, country)}
                          </td>
                          <td
                            className={`px-2.5 py-1.5 text-right ${
                              isProfit ? "text-primary" : "text-destructive"
                            }`}
                          >
                            {isProfit ? "+" : ""}{fmtCurrency(netProfit, country)}
                          </td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  {/* Payout history */}
                  <div>
                    <p className="text-xs font-bold pl-2 border-l-2 border-primary mb-2">
                      Payout History
                    </p>
                    <table className="w-full text-xs border-collapse">
                      <thead>
                        <tr className="bg-primary text-primary-foreground">
                          {["Prop Firm", "Account No.", "Date", "Amount"].map((h) => (
                            <th
                              key={h}
                              className="px-2.5 py-1.5 text-left font-semibold text-[10px]"
                            >
                              {h}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {accounts.every((a) => !a.payoutHistory?.length) ? (
                          <tr>
                            <td
                              colSpan={4}
                              className="text-center text-muted-foreground py-3 text-xs"
                            >
                              No payouts recorded
                            </td>
                          </tr>
                        ) : (
                          accounts.flatMap((acc) =>
                            (acc.payoutHistory || []).map((p, i) => (
                              <tr
                                key={`${acc.id}-${i}`}
                                className="border-b border-border even:bg-muted/30"
                              >
                                <td className="px-2.5 py-1.5">{acc.propFirm}</td>
                                <td className="px-2.5 py-1.5">{acc.accountNumber}</td>
                                <td className="px-2.5 py-1.5">
                                  {new Date(p.date).toLocaleDateString(country.dateLocale, { year: "numeric", month: "short", day: "numeric" })}
                                </td>
                                <td className="px-2.5 py-1.5 text-right font-semibold text-green-600">
                                  + {fmtCurrency(p.amount || 0, country)}
                                </td>
                              </tr>
                            ))
                          )
                        )}
                      </tbody>
                    </table>
                  </div>

                  <p className="text-[9px] text-muted-foreground italic border-t border-border pt-3 leading-relaxed">
                    {country.disclaimer}
                  </p>
                </div>
              </ScrollArea>
            </TabsContent>
          </Tabs>

          {/* Footer with Download Button */}
          <div className="px-6 py-4 border-t border-border bg-muted/30 rounded-b-lg flex-shrink-0">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs text-muted-foreground">
                Opens in browser – use{" "}
                <kbd className="rounded bg-muted px-1 py-0.5 text-[10px] font-mono">
                  Cmd+P
                </kbd>{" "}
                to save as PDF.
              </p>
              <Button onClick={generateAndPrint} className="gap-2 shrink-0">
                <Printer className="h-4 w-4" />
                Create PDF &amp; Print
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
