import { motion } from "framer-motion";
import {
  Wallet,
  ArrowUpRight,
  ArrowDownLeft,
  TrendingUp,
  ChevronRight,
  FileText,
  User,
  MapPin,
  Hash,
  CalendarDays,
  Briefcase,
  Printer,
  Globe,
  Plus,
  Trash2,
  PlusCircle,
  MinusCircle,
} from "lucide-react";
import { useEffect, useState } from "react";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";

interface PropFirmAccount {
  id: string;
  propFirm: string;
  accountNumber: string;
  initialCost?: number;
  payoutHistory?: Array<{ date: string; amount: number }>;
  balance?: number;
  [key: string]: any;
}

interface TaxInfo {
  fullName: string;
  address: string;
  city: string;
  taxNumber: string;
  taxAdvisor: string;
  taxYear: string;
}

const TAX_STORAGE_KEY = "cw_tax_info";

interface CountryConfig {
  code: string;
  flag: string;
  name: string;
  currency: string;
  currencySymbol: string;
  currencyPosition: "before" | "after";
  locale: string;
  dateLocale: string;
  taxIdLabel: string;
  taxIdPlaceholder: string;
  taxAdvisorLabel: string;
  cityLabel: string;
  cityPlaceholder: string;
  streetPlaceholder: string;
  disclaimer: string;
}

const COUNTRIES: CountryConfig[] = [
  {
    code: "DE",
    flag: "🇩🇪",
    name: "Germany",
    currency: "EUR",
    currencySymbol: "€",
    currencyPosition: "after",
    locale: "de-DE",
    dateLocale: "de-DE",
    taxIdLabel: "Tax Number (Steuernummer)",
    taxIdPlaceholder: "12/345/67890",
    taxAdvisorLabel: "Tax Advisor (Steuerberater)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "10115 Berlin",
    streetPlaceholder: "Musterstraße 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace professional tax advice (§ 4 StBerG). Please verify all figures with your Steuerberater.",
  },
  {
    code: "AT",
    flag: "🇦🇹",
    name: "Austria",
    currency: "EUR",
    currencySymbol: "€",
    currencyPosition: "after",
    locale: "de-AT",
    dateLocale: "de-AT",
    taxIdLabel: "Tax Number (Steuernummer)",
    taxIdPlaceholder: "12 345/6789",
    taxAdvisorLabel: "Tax Advisor (Steuerberater)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "1010 Wien",
    streetPlaceholder: "Musterstraße 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace professional tax advice. Please verify all figures with your Steuerberater.",
  },
  {
    code: "CH",
    flag: "🇨🇭",
    name: "Switzerland",
    currency: "CHF",
    currencySymbol: "CHF",
    currencyPosition: "before",
    locale: "de-CH",
    dateLocale: "de-CH",
    taxIdLabel: "Tax ID (AHV-Nummer / UID)",
    taxIdPlaceholder: "756.1234.5678.90",
    taxAdvisorLabel: "Tax Advisor (Treuhänder)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "8001 Zürich",
    streetPlaceholder: "Musterstrasse 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace professional tax advice. Please verify all figures with your Treuhänder.",
  },
  {
    code: "US",
    flag: "🇺🇸",
    name: "United States",
    currency: "USD",
    currencySymbol: "$",
    currencyPosition: "before",
    locale: "en-US",
    dateLocale: "en-US",
    taxIdLabel: "SSN / EIN",
    taxIdPlaceholder: "XXX-XX-XXXX",
    taxAdvisorLabel: "CPA / Tax Advisor",
    cityLabel: "City, State ZIP",
    cityPlaceholder: "New York, NY 10001",
    streetPlaceholder: "123 Main Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not constitute tax advice or replace consultation with a qualified CPA or tax professional.",
  },
  {
    code: "GB",
    flag: "🇬🇧",
    name: "United Kingdom",
    currency: "GBP",
    currencySymbol: "£",
    currencyPosition: "before",
    locale: "en-GB",
    dateLocale: "en-GB",
    taxIdLabel: "UTR / National Insurance No.",
    taxIdPlaceholder: "1234567890",
    taxAdvisorLabel: "Accountant / Tax Advisor",
    cityLabel: "City & Postcode",
    cityPlaceholder: "London, EC1A 1BB",
    streetPlaceholder: "12 Example Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace advice from a qualified accountant or HMRC guidance.",
  },
  {
    code: "NL",
    flag: "🇳🇱",
    name: "Netherlands",
    currency: "EUR",
    currencySymbol: "€",
    currencyPosition: "after",
    locale: "nl-NL",
    dateLocale: "nl-NL",
    taxIdLabel: "BSN / RSIN",
    taxIdPlaceholder: "123456789",
    taxAdvisorLabel: "Tax Advisor (Belastingadviseur)",
    cityLabel: "ZIP & City",
    cityPlaceholder: "1234 AB Amsterdam",
    streetPlaceholder: "Voorbeeldstraat 12",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not replace advice from a qualified belastingadviseur.",
  },
  {
    code: "AU",
    flag: "🇦🇺",
    name: "Australia",
    currency: "AUD",
    currencySymbol: "A$",
    currencyPosition: "before",
    locale: "en-AU",
    dateLocale: "en-AU",
    taxIdLabel: "TFN / ABN",
    taxIdPlaceholder: "123 456 789",
    taxAdvisorLabel: "Tax Agent / Accountant",
    cityLabel: "City, State Postcode",
    cityPlaceholder: "Sydney NSW 2000",
    streetPlaceholder: "12 Example Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not constitute tax advice. Please consult a registered tax agent.",
  },
  {
    code: "CA",
    flag: "🇨🇦",
    name: "Canada",
    currency: "CAD",
    currencySymbol: "C$",
    currencyPosition: "before",
    locale: "en-CA",
    dateLocale: "en-CA",
    taxIdLabel: "SIN / Business Number",
    taxIdPlaceholder: "123 456 789",
    taxAdvisorLabel: "CPA / Tax Advisor",
    cityLabel: "City, Province Postal Code",
    cityPlaceholder: "Toronto, ON M5V 3A8",
    streetPlaceholder: "123 Main Street",
    disclaimer: "This report was automatically generated by CycleWise and serves as a summary of prop firm trading activities. It does not constitute tax advice under the Income Tax Act. Please consult a qualified CPA.",
  },
];

const fmtCurrency = (n: number, country: CountryConfig) => {
  const formatted = n.toLocaleString(country.locale, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  return country.currencyPosition === "before"
    ? `${country.currencySymbol}${formatted}`
    : `${formatted} ${country.currencySymbol}`;
};

const fmt = (n: number) =>
  n.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export function PropFirmSummary() {
  const [totalExpenses, setTotalExpenses] = useState(0);
  const [totalPayouts, setTotalPayouts] = useState(0);
  const [accountCount, setAccountCount] = useState(0);
  const [accounts, setAccounts] = useState<PropFirmAccount[]>([]);
  const [open, setOpen] = useState(false);
  const [openFinanceId, setOpenFinanceId] = useState<string | null>(null);
  const [editCost, setEditCost] = useState("");
  const [newPayoutAmount, setNewPayoutAmount] = useState("");
  const [newPayoutDate, setNewPayoutDate] = useState(new Date().toISOString().split("T")[0]);
  const [newFirmName, setNewFirmName] = useState("");
  const [newAccountNumber, setNewAccountNumber] = useState("");
  const [newAccountCost, setNewAccountCost] = useState("");
  const [countryCode, setCountryCode] = useState("US");
  const country = COUNTRIES.find((c) => c.code === countryCode) ?? COUNTRIES[3];
  const [taxInfo, setTaxInfo] = useState<TaxInfo>({
    fullName: "",
    address: "",
    city: "",
    taxNumber: "",
    taxAdvisor: "",
    taxYear: String(new Date().getFullYear()),
  });

  // Load tax info & country from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem(TAX_STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed.countryCode) setCountryCode(parsed.countryCode);
        setTaxInfo(parsed);
      }
    } catch {}
  }, []);

  const updateCountry = (code: string) => {
    setCountryCode(code);
    const updated = { ...taxInfo, countryCode: code };
    localStorage.setItem(TAX_STORAGE_KEY, JSON.stringify(updated));
  };

  const saveAccountsAndRecalc = (updated: PropFirmAccount[]) => {
    localStorage.setItem("cw_propfirm_accounts", JSON.stringify(updated));
    let expenses = 0, payouts = 0;
    updated.forEach((acc) => {
      if (acc.initialCost) expenses += acc.initialCost;
      (acc.payoutHistory || []).forEach((p) => { payouts += p.amount || 0; });
    });
    setAccounts(updated);
    setTotalExpenses(expenses);
    setTotalPayouts(payouts);
    setAccountCount(updated.length);
  };

  const addManualAccount = () => {
    if (!newFirmName.trim()) return;
    const cost = parseFloat(newAccountCost);
    const newAcc: PropFirmAccount = {
      id: Date.now().toString(),
      propFirm: newFirmName.trim(),
      accountNumber: newAccountNumber.trim() || "–",
      initialCost: isNaN(cost) || cost < 0 ? 0 : cost,
      payoutHistory: [],
      status: "disconnected",
    };
    saveAccountsAndRecalc([...accounts, newAcc]);
    setNewFirmName("");
    setNewAccountNumber("");
    setNewAccountCost("");
  };

  const removeManualAccount = (id: string) => {
    saveAccountsAndRecalc(accounts.filter((a) => a.id !== id));
    if (openFinanceId === id) setOpenFinanceId(null);
  };

  const saveCost = (id: string) => {
    const cost = parseFloat(editCost);
    if (isNaN(cost) || cost < 0) return;
    saveAccountsAndRecalc(accounts.map((a) => a.id === id ? { ...a, initialCost: cost } : a));
  };

  const addPayout = (id: string) => {
    const amount = parseFloat(newPayoutAmount);
    if (isNaN(amount) || amount <= 0 || !newPayoutDate) return;
    saveAccountsAndRecalc(
      accounts.map((a) =>
        a.id === id
          ? { ...a, payoutHistory: [...(a.payoutHistory || []), { date: newPayoutDate, amount }].sort((x, y) => x.date < y.date ? 1 : -1) }
          : a
      )
    );
    setNewPayoutAmount("");
  };

  const removePayout = (accountId: string, idx: number) => {
    saveAccountsAndRecalc(
      accounts.map((a) =>
        a.id === accountId
          ? { ...a, payoutHistory: (a.payoutHistory || []).filter((_, i) => i !== idx) }
          : a
      )
    );
  };

  // Load prop firm accounts on mount
  useEffect(() => {
    try {
      const raw = localStorage.getItem("cw_propfirm_accounts");
      const accs: PropFirmAccount[] = raw ? JSON.parse(raw) : [];
      let expenses = 0, payouts = 0;
      accs.forEach((acc) => {
        if (acc.initialCost) expenses += acc.initialCost;
        (acc.payoutHistory || []).forEach((p) => { payouts += p.amount || 0; });
      });
      setAccounts(accs);
      setTotalExpenses(expenses);
      setTotalPayouts(payouts);
      setAccountCount(accs.length);
    } catch (err) {
      console.error("Error loading prop firm accounts:", err);
    }
  }, []);

  const updateField = (field: keyof TaxInfo, value: string) => {
    const updated = { ...taxInfo, [field]: value };
    setTaxInfo(updated);
    localStorage.setItem(TAX_STORAGE_KEY, JSON.stringify({ ...updated, countryCode }));
  };

  const netProfit = totalPayouts - totalExpenses;
  const roi = totalExpenses > 0 ? ((netProfit / totalExpenses) * 100).toFixed(1) : "0";
  const isProfit = netProfit >= 0;

  const generateAndPrint = () => {
    const c = country;
    const dateStr = new Date().toLocaleDateString(c.dateLocale, { year: "numeric", month: "long", day: "numeric" });
    const fmtAmt = (n: number) => fmtCurrency(n, c);

    let accountRows = "";
    accounts.forEach((acc) => {
      const payoutsSum = (acc.payoutHistory || []).reduce(
        (s, p) => s + (p.amount || 0), 0
      );
      const net = payoutsSum - (acc.initialCost || 0);
      accountRows += `
        <tr>
          <td>${acc.propFirm}</td>
          <td>${acc.accountNumber}</td>
          <td class="num">- ${fmtAmt(acc.initialCost || 0)}</td>
          <td class="num pos">+ ${fmtAmt(payoutsSum)}</td>
          <td class="num ${net >= 0 ? "pos" : "neg"}">${net >= 0 ? "+" : ""}${fmtAmt(net)}</td>
        </tr>`;
    });

    let payoutRows = "";
    accounts.forEach((acc) => {
      (acc.payoutHistory || []).forEach((p) => {
        payoutRows += `
          <tr>
            <td>${acc.propFirm}</td>
            <td>${acc.accountNumber}</td>
            <td>${new Date(p.date).toLocaleDateString(c.dateLocale, { year: "numeric", month: "short", day: "numeric" })}</td>
            <td class="num pos">+ ${fmtAmt(p.amount || 0)}</td>
          </tr>`;
      });
    });

    if (!payoutRows) {
      payoutRows = `<tr><td colspan="4" style="text-align:center;color:#aaa;padding:16px">No payouts recorded</td></tr>`;
    }

    const positiveColor = isProfit ? "#3730a3" : "#c62828";
    const positiveBg = isProfit ? "#f0f0ff" : "#fff0f0";
    const positiveBorder = isProfit ? "#c8c0ff" : "#ffcccc";

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Tax Report ${taxInfo.taxYear} – ${taxInfo.fullName || "Trader"}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 10.5pt; color: #111; background: #fff; }
    .page { max-width: 210mm; margin: 0 auto; padding: 18mm 22mm 16mm; }

    /* Header */
    .header { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 1px solid #111; padding-bottom: 10px; margin-bottom: 20px; }
    .logo { font-size: 14pt; font-weight: 800; letter-spacing: -0.3px; color: #111; }
    .doc-title { text-align: right; }
    .doc-title h1 { font-size: 12pt; font-weight: 700; color: #111; }
    .doc-title p { font-size: 8.5pt; color: #555; margin-top: 2px; }

    /* Meta */
    .meta-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0; margin-bottom: 20px; border: 1px solid #ccc; }
    .meta-box { padding: 11px 14px; }
    .meta-box:first-child { border-right: 1px solid #ccc; }
    .meta-box h3 { font-size: 7pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; color: #555; margin-bottom: 8px; }
    .meta-row { display: flex; justify-content: space-between; font-size: 9.5pt; margin-bottom: 3px; gap: 8px; }
    .meta-row .lbl { color: #555; flex-shrink: 0; }
    .meta-row .val { font-weight: 600; color: #111; text-align: right; }

    /* Summary */
    .summary { display: grid; grid-template-columns: repeat(4, 1fr); border: 1px solid #ccc; margin-bottom: 22px; }
    .sc { padding: 11px 10px; text-align: center; border-right: 1px solid #ccc; }
    .sc:last-child { border-right: none; }
    .sc .sc-lbl { font-size: 7pt; color: #555; text-transform: uppercase; letter-spacing: 0.4px; margin-bottom: 5px; }
    .sc .sc-val { font-size: 12pt; font-weight: 700; color: #111; }

    /* Sections */
    section { margin-bottom: 22px; }
    section h2 { font-size: 9pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.6px; color: #111; border-bottom: 1px solid #111; padding-bottom: 4px; margin-bottom: 0; }
    table { width: 100%; border-collapse: collapse; font-size: 9.5pt; }
    th { background: #f4f4f4; color: #111; padding: 7px 10px; text-align: left; font-weight: 600; font-size: 8pt; text-transform: uppercase; letter-spacing: 0.3px; border-bottom: 1px solid #ccc; }
    th.num, td.num { text-align: right; }
    td { padding: 7px 10px; border-bottom: 1px solid #e8e8e8; color: #111; }
    tr:last-child td { border-bottom: none; }
    .total-row td { font-weight: 700; border-top: 1px solid #111; border-bottom: none; background: #f9f9f9; }

    /* Footer */
    .footer { margin-top: 24px; padding-top: 8px; border-top: 1px solid #ccc; display: flex; justify-content: space-between; font-size: 7.5pt; color: #888; }
    .disclaimer { font-size: 7pt; color: #888; margin-top: 10px; line-height: 1.6; border-top: 1px solid #ccc; padding-top: 8px; }
    .disclaimer strong { color: #555; }
    .disclaimer .disc-title { font-weight: 700; color: #444; font-style: normal; margin-bottom: 4px; display: block; }

    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .page { padding: 12mm 18mm; }
    }
  </style>
</head>
<body>
<div class="page">
  <div class="header">
    <div class="logo">CycleWise</div>
    <div class="doc-title">
      <h1>Prop Firm Tax Report</h1>
      <p>Tax Year ${taxInfo.taxYear} &nbsp;&#183;&nbsp; ${dateStr}</p>
    </div>
  </div>

  <div class="meta-grid">
    <div class="meta-box">
      <h3>Taxpayer</h3>
      <div class="meta-row"><span class="lbl">Name</span><span class="val">${taxInfo.fullName || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">Address</span><span class="val">${taxInfo.address || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">${c.cityLabel}</span><span class="val">${taxInfo.city || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">${c.taxIdLabel}</span><span class="val">${taxInfo.taxNumber || "&#8211;"}</span></div>
    </div>
    <div class="meta-box">
      <h3>Document</h3>
      <div class="meta-row"><span class="lbl">Tax Year</span><span class="val">${taxInfo.taxYear}</span></div>
      <div class="meta-row"><span class="lbl">Country</span><span class="val">${c.name}</span></div>
      <div class="meta-row"><span class="lbl">${c.taxAdvisorLabel}</span><span class="val">${taxInfo.taxAdvisor || "&#8211;"}</span></div>
      <div class="meta-row"><span class="lbl">Accounts</span><span class="val">${accountCount}</span></div>
    </div>
  </div>

  <div class="summary">
    <div class="sc">
      <div class="sc-lbl">Expenses</div>
      <div class="sc-val">- ${fmtAmt(totalExpenses)}</div>
    </div>
    <div class="sc">
      <div class="sc-lbl">Income (Payouts)</div>
      <div class="sc-val">+ ${fmtAmt(totalPayouts)}</div>
    </div>
    <div class="sc">
      <div class="sc-lbl">Net Profit / Loss</div>
      <div class="sc-val">${isProfit ? "+" : ""}${fmtAmt(netProfit)}</div>
    </div>
    <div class="sc">
      <div class="sc-lbl">ROI</div>
      <div class="sc-val">${roi} %</div>
    </div>
  </div>

  <section>
    <h2>Account Overview</h2>
    <table>
      <thead>
        <tr>
          <th>Prop Firm</th>
          <th>Account No.</th>
          <th class="num">Expenses</th>
          <th class="num">Income</th>
          <th class="num">Net</th>
        </tr>
      </thead>
      <tbody>
        ${accountRows || '<tr><td colspan="5" style="text-align:center;color:#aaa;padding:14px">No accounts recorded</td></tr>'}
        <tr class="total-row">
          <td colspan="2">Total</td>
          <td class="num">- ${fmtAmt(totalExpenses)}</td>
          <td class="num">+ ${fmtAmt(totalPayouts)}</td>
          <td class="num">${isProfit ? "+" : ""}${fmtAmt(netProfit)}</td>
        </tr>
      </tbody>
    </table>
  </section>

  <section>
    <h2>Payout History</h2>
    <table>
      <thead>
        <tr>
          <th>Prop Firm</th>
          <th>Account No.</th>
          <th>Date</th>
          <th class="num">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${payoutRows}
      </tbody>
    </table>
  </section>

  <div class="footer">
    <span>${taxInfo.fullName || "Trader"} &nbsp;&#183;&nbsp; Tax Year ${taxInfo.taxYear}</span>
    <span>Generated by CycleWise &nbsp;&#183;&nbsp; ${dateStr}</span>
  </div>
  <div class="disclaimer">
    <span class="disc-title">DISCLAIMER &amp; LIMITATION OF LIABILITY</span>
    This document was automatically generated by CycleWise solely for informational and organizational purposes. All data was entered manually by the user and has <strong>not been verified, audited, or confirmed</strong> by CycleWise or any affiliated party. <strong>CycleWise expressly disclaims all liability</strong> for any errors, omissions, inaccuracies, or incompleteness of the information presented in this document.
    <br/><br/>
    This document does <strong>not constitute tax advice, legal advice, or financial advice</strong> of any kind and must not be relied upon as such. ${c.disclaimer}
    <br/><br/>
    The user is solely responsible for verifying the accuracy of all figures and for complying with applicable tax laws and regulations. CycleWise, its developers, operators, and contributors shall not be held liable for any damages, penalties, fines, or legal consequences of any nature arising from the use of or reliance on this document. <strong>Always consult a licensed and qualified tax professional</strong> before submitting any tax-related documentation to authorities.
  </div>
</div>
</body>
</html>`;

    const newWin = window.open("", "_blank");
    if (newWin) {
      newWin.document.write(html);
      newWin.document.close();
      setTimeout(() => newWin.print(), 600);
    }
  };

  return (
    <>
      {/* Clickable Summary Card */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        onClick={() => setOpen(true)}
        className="cursor-pointer rounded-2xl bg-gradient-to-br from-secondary/50 to-accent/30 p-5 transition-all hover:ring-2 hover:ring-primary/40 hover:shadow-lg"
      >
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-card p-2.5">
              <Wallet className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h3 className="font-semibold text-foreground">Prop Firm Summary</h3>
              <p className="text-xs text-muted-foreground">
                {accountCount} {accountCount === 1 ? "account" : "accounts"} · Create tax report
              </p>
            </div>
          </div>
          <div className="flex items-center gap-1 rounded-lg bg-card/70 px-2.5 py-1.5">
            <FileText className="h-3.5 w-3.5 text-primary" />
            <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />
          </div>
        </div>

        <div className="mt-4 grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <ArrowDownLeft className="h-3 w-3" />
              Expenses
            </div>
            <p className="text-lg font-semibold text-foreground tabular-nums">
              ${totalExpenses.toLocaleString()}
            </p>
          </div>
          <div className="space-y-1">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <ArrowUpRight className="h-3 w-3" />
              Payouts
            </div>
            <p className="text-lg font-semibold text-foreground tabular-nums">
              ${totalPayouts.toLocaleString()}
            </p>
          </div>
        </div>

        <div className="mt-4 rounded-xl bg-card/60 p-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-xs text-muted-foreground">Net Profit</p>
              <p
                className={`text-2xl font-bold tabular-nums ${
                  isProfit ? "text-accent-foreground" : "text-destructive"
                }`}
              >
                {isProfit ? "+" : "-"}${Math.abs(netProfit).toLocaleString()}
              </p>
            </div>
            <div
              className={`flex items-center gap-1 rounded-lg px-3 py-1.5 tabular-nums ${
                isProfit
                  ? "bg-accent/50 text-accent-foreground"
                  : "bg-destructive/10 text-destructive"
              }`}
            >
              <TrendingUp className="h-4 w-4" />
              <span className="text-sm font-semibold">{roi}% ROI</span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Tax Report Dialog */}
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-w-2xl max-h-[90vh] flex flex-col gap-0 p-0">
          <DialogHeader className="px-6 pt-6 pb-4 border-b border-border">
            <div className="flex items-center gap-3">
              <div className="rounded-xl bg-primary/10 p-2.5">
                <FileText className="h-5 w-5 text-primary" />
              </div>
              <div>
                <DialogTitle className="text-lg font-semibold">
                  Create Tax Report
                </DialogTitle>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Professional document for your tax advisor
                </p>
              </div>
            </div>
          </DialogHeader>

          <Tabs defaultValue="accounts" className="flex flex-col flex-1 min-h-0">
            <TabsList className="mx-6 mt-4 mb-0 grid grid-cols-3">
              <TabsTrigger value="accounts" className="gap-1.5">
                <Wallet className="h-3.5 w-3.5" />
                Accounts
              </TabsTrigger>
              <TabsTrigger value="data" className="gap-1.5">
                <User className="h-3.5 w-3.5" />
                My Details
              </TabsTrigger>
              <TabsTrigger value="preview" className="gap-1.5">
                <FileText className="h-3.5 w-3.5" />
                Preview
              </TabsTrigger>
            </TabsList>

            {/* TAB: Accounts */}
            <TabsContent value="accounts" className="overflow-auto px-6 pb-4 mt-0">
              <p className="text-xs text-muted-foreground mt-4 mb-4">
                Add your prop firm accounts manually and enter costs &amp; payouts. No MT4/MT5 connection needed.
              </p>

              {/* Account list */}
              <div className="space-y-3 mb-4">
                {accounts.length === 0 && (
                  <div className="rounded-xl border border-dashed border-border p-6 text-center">
                    <div className="text-3xl mb-2">🏦</div>
                    <p className="text-sm text-muted-foreground">No accounts yet. Add one below.</p>
                  </div>
                )}
                {accounts.map((acc) => {
                  const totalPay = (acc.payoutHistory || []).reduce((s, p) => s + (p.amount || 0), 0);
                  const net = totalPay - (acc.initialCost || 0);
                  return (
                    <div key={acc.id} className="rounded-xl border bg-card">
                      {/* Account header */}
                      <div className="flex items-center justify-between px-4 py-3">
                        <div>
                          <p className="font-semibold text-sm text-foreground">{acc.propFirm}</p>
                          <p className="text-xs text-muted-foreground">{acc.accountNumber}</p>
                        </div>
                        <div className="flex items-center gap-3 text-xs">
                          <span className="text-destructive tabular-nums">-{fmtCurrency(acc.initialCost || 0, country)}</span>
                          <span className="text-green-600 tabular-nums">+{fmtCurrency(totalPay, country)}</span>
                          <span className={`font-bold tabular-nums ${net >= 0 ? "text-primary" : "text-destructive"}`}>
                            {net >= 0 ? "+" : ""}{fmtCurrency(net, country)}
                          </span>
                          <button
                            onClick={() => {
                              if (openFinanceId === acc.id) {
                                setOpenFinanceId(null);
                              } else {
                                setOpenFinanceId(acc.id);
                                setEditCost(acc.initialCost != null ? String(acc.initialCost) : "");
                                setNewPayoutAmount("");
                                setNewPayoutDate(new Date().toISOString().split("T")[0]);
                              }
                            }}
                            className="rounded-lg bg-muted px-2 py-1 hover:bg-muted/80 transition-colors text-muted-foreground hover:text-foreground"
                          >
                            {openFinanceId === acc.id ? "▲ Close" : "✎ Edit"}
                          </button>
                          <button
                            onClick={() => removeManualAccount(acc.id)}
                            className="text-muted-foreground hover:text-destructive transition-colors"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </div>

                      {/* Finance panel */}
                      {openFinanceId === acc.id && (
                        <div className="border-t border-border/60 px-4 pb-4 pt-3 space-y-4 bg-muted/20 rounded-b-xl">
                          {/* Cost */}
                          <div>
                            <Label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Challenge / Account Cost</Label>
                            <div className="flex gap-2 mt-1.5">
                              <Input
                                type="number" min="0" step="0.01"
                                value={editCost}
                                onChange={(e) => setEditCost(e.target.value)}
                                placeholder="e.g. 149.00"
                                className="max-w-[160px] h-8 text-sm"
                              />
                              <Button size="sm" className="h-8" onClick={() => saveCost(acc.id)}>Save</Button>
                            </div>
                          </div>

                          {/* Payouts */}
                          <div>
                            <Label className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Payouts Received</Label>
                            {(acc.payoutHistory || []).length > 0 ? (
                              <div className="mt-1.5 space-y-1">
                                {(acc.payoutHistory || []).map((p, i) => (
                                  <div key={i} className="flex items-center justify-between rounded-lg bg-green-500/10 border border-green-500/20 px-3 py-1.5">
                                    <span className="text-sm font-semibold text-green-600">+{fmtCurrency(p.amount, country)}</span>
                                    <span className="text-xs text-muted-foreground">
                                      {new Date(p.date).toLocaleDateString(country.dateLocale, { year: "numeric", month: "short", day: "numeric" })}
                                    </span>
                                    <button onClick={() => removePayout(acc.id, i)} className="text-muted-foreground hover:text-destructive transition-colors">
                                      <MinusCircle className="h-3.5 w-3.5" />
                                    </button>
                                  </div>
                                ))}
                              </div>
                            ) : (
                              <p className="text-xs text-muted-foreground mt-1 italic">No payouts yet.</p>
                            )}
                            <div className="flex gap-2 mt-2 flex-wrap">
                              <Input
                                type="number" min="0" step="0.01"
                                value={newPayoutAmount}
                                onChange={(e) => setNewPayoutAmount(e.target.value)}
                                placeholder="Amount"
                                className="w-[110px] h-8 text-sm"
                              />
                              <Input
                                type="date"
                                value={newPayoutDate}
                                onChange={(e) => setNewPayoutDate(e.target.value)}
                                className="w-[140px] h-8 text-sm"
                              />
                              <Button
                                size="sm" variant="outline" className="h-8 gap-1.5 text-green-600 border-green-500/40 hover:bg-green-500/10"
                                onClick={() => addPayout(acc.id)}
                              >
                                <PlusCircle className="h-3.5 w-3.5" />
                                Add Payout
                              </Button>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>

              <Separator className="mb-4" />

              {/* Add new account */}
              <div>
                <p className="text-xs font-semibold text-muted-foreground uppercase tracking-wide mb-2">Add Account</p>
                <div className="flex gap-2 flex-wrap">
                  <Input
                    placeholder="Prop Firm (e.g. FTMO)"
                    value={newFirmName}
                    onChange={(e) => setNewFirmName(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && addManualAccount()}
                    className="flex-1 min-w-[130px]"
                  />
                  <Input
                    placeholder="Account # (optional)"
                    value={newAccountNumber}
                    onChange={(e) => setNewAccountNumber(e.target.value)}
                    onKeyDown={(e) => e.key === "Enter" && addManualAccount()}
                    className="flex-1 min-w-[130px]"
                  />
                  <div className="relative min-w-[120px] flex-1">
                    <Input
                      type="number"
                      min="0"
                      step="0.01"
                      placeholder="Cost"
                      value={newAccountCost}
                      onChange={(e) => setNewAccountCost(e.target.value)}
                      onKeyDown={(e) => e.key === "Enter" && addManualAccount()}
                      className="pr-9"
                    />
                    <span className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground text-sm pointer-events-none">{country.currencySymbol}</span>
                  </div>
                  <Button onClick={addManualAccount} className="gap-1.5 shrink-0">
                    <Plus className="h-4 w-4" />
                    Add
                  </Button>
                </div>
              </div>
            </TabsContent>

            {/* TAB: Personal Data */}
            <TabsContent value="data" className="overflow-auto px-6 pb-2 mt-0">
              <p className="text-xs text-muted-foreground mt-4 mb-5">
                These details appear in the tax report and are saved locally.
              </p>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <Label className="flex items-center gap-1.5 text-sm">
                    <Globe className="h-3.5 w-3.5 text-muted-foreground" />
                    Country
                  </Label>
                  <Select value={countryCode} onValueChange={updateCountry}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {COUNTRIES.map((c) => (
                        <SelectItem key={c.code} value={c.code}>
                          <span className="flex items-center gap-2">
                            <span>{c.flag}</span>
                            <span>{c.name}</span>
                            <span className="text-muted-foreground text-xs">({c.currency})</span>
                          </span>
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1.5">
                  <Label className="flex items-center gap-1.5 text-sm">
                    <User className="h-3.5 w-3.5 text-muted-foreground" />
                    Full Name
                  </Label>
                  <Input
                    placeholder="John Smith"
                    value={taxInfo.fullName}
                    onChange={(e) => updateField("fullName", e.target.value)}
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="flex items-center gap-1.5 text-sm">
                      <MapPin className="h-3.5 w-3.5 text-muted-foreground" />
                      Street &amp; Number
                    </Label>
                    <Input
                      placeholder={country.streetPlaceholder}
                      value={taxInfo.address}
                      onChange={(e) => updateField("address", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-sm">{country.cityLabel}</Label>
                    <Input
                      placeholder={country.cityPlaceholder}
                      value={taxInfo.city}
                      onChange={(e) => updateField("city", e.target.value)}
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1.5">
                    <Label className="flex items-center gap-1.5 text-sm">
                      <Hash className="h-3.5 w-3.5 text-muted-foreground" />
                      {country.taxIdLabel}
                    </Label>
                    <Input
                      placeholder={country.taxIdPlaceholder}
                      value={taxInfo.taxNumber}
                      onChange={(e) => updateField("taxNumber", e.target.value)}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="flex items-center gap-1.5 text-sm">
                      <CalendarDays className="h-3.5 w-3.5 text-muted-foreground" />
                      Tax Year
                    </Label>
                    <Input
                      placeholder="2025"
                      value={taxInfo.taxYear}
                      onChange={(e) => updateField("taxYear", e.target.value)}
                    />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <Label className="flex items-center gap-1.5 text-sm">
                    <Briefcase className="h-3.5 w-3.5 text-muted-foreground" />
                    {country.taxAdvisorLabel} (optional)
                  </Label>
                  <Input
                    placeholder={`e.g. Smith & Partners`}
                    value={taxInfo.taxAdvisor}
                    onChange={(e) => updateField("taxAdvisor", e.target.value)}
                  />
                </div>

                <Separator />

                <div className="rounded-xl bg-muted/50 p-4">
                  <p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground mb-3">
                    Financial Summary in Report
                  </p>
                  <div className="grid grid-cols-3 gap-3">
                    <div className="rounded-lg bg-destructive/10 p-3 text-center">
                      <p className="text-[10px] text-muted-foreground mb-1">Expenses</p>
                      <p className="font-bold text-destructive tabular-nums text-sm">
                        - {fmtCurrency(totalExpenses, country)}
                      </p>
                    </div>
                    <div className="rounded-lg bg-green-500/10 p-3 text-center">
                      <p className="text-[10px] text-muted-foreground mb-1">Income</p>
                      <p className="font-bold text-green-600 tabular-nums text-sm">
                        + {fmtCurrency(totalPayouts, country)}
                      </p>
                    </div>
                    <div
                      className={`rounded-lg p-3 text-center ${
                        isProfit ? "bg-primary/10" : "bg-destructive/10"
                      }`}
                    >
                      <p className="text-[10px] text-muted-foreground mb-1">Net</p>
                      <p
                        className={`font-bold tabular-nums text-sm ${
                          isProfit ? "text-primary" : "text-destructive"
                        }`}
                      >
                        {isProfit ? "+" : ""}{fmtCurrency(netProfit, country)}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </TabsContent>

            {/* TAB: Preview */}
            <TabsContent value="preview" className="min-h-0 px-6 pb-2 mt-0">
              <ScrollArea className="h-[400px] mt-4 rounded border border-border">
                <div className="p-5 space-y-4 font-sans text-xs text-foreground bg-background">

                  {/* Header */}
                  <div className="flex items-end justify-between border-b border-foreground pb-3">
                    <span className="text-sm font-black tracking-tight">CycleWise</span>
                    <div className="text-right">
                      <p className="font-bold text-sm">Prop Firm Tax Report</p>
                      <p className="text-[10px] text-muted-foreground">
                        Tax Year {taxInfo.taxYear} · {new Date().toLocaleDateString(country.dateLocale, { year: "numeric", month: "long", day: "numeric" })}
                      </p>
                    </div>
                  </div>

                  {/* Meta grid */}
                  <div className="grid grid-cols-2 border border-border">
                    {[
                      {
                        title: "Taxpayer",
                        rows: [
                          ["Name", taxInfo.fullName || "–"],
                          ["Address", taxInfo.address || "–"],
                          [country.cityLabel, taxInfo.city || "–"],
                          [country.taxIdLabel, taxInfo.taxNumber || "–"],
                        ],
                      },
                      {
                        title: "Document",
                        rows: [
                          ["Tax Year", taxInfo.taxYear],
                          ["Country", country.name],
                          [country.taxAdvisorLabel, taxInfo.taxAdvisor || "–"],
                          ["Accounts", String(accountCount)],
                        ],
                      },
                    ].map((box, bi) => (
                      <div key={box.title} className={`p-3 space-y-1 ${bi === 0 ? "border-r border-border" : ""}`}>
                        <p className="text-[8px] font-bold uppercase tracking-widest text-muted-foreground mb-2">{box.title}</p>
                        {box.rows.map(([label, value]) => (
                          <div key={label} className="flex justify-between gap-2">
                            <span className="text-muted-foreground">{label}</span>
                            <span className="font-semibold text-right">{value}</span>
                          </div>
                        ))}
                      </div>
                    ))}
                  </div>

                  {/* Summary row */}
                  <div className="grid grid-cols-4 border border-border">
                    {[
                      { label: "Expenses", value: `- ${fmtCurrency(totalExpenses, country)}` },
                      { label: "Income (Payouts)", value: `+ ${fmtCurrency(totalPayouts, country)}` },
                      { label: "Net Profit / Loss", value: `${isProfit ? "+" : ""}${fmtCurrency(netProfit, country)}` },
                      { label: "ROI", value: `${roi} %` },
                    ].map((item, i) => (
                      <div key={item.label} className={`p-2.5 text-center ${i < 3 ? "border-r border-border" : ""}`}>
                        <p className="text-[8px] uppercase text-muted-foreground mb-1">{item.label}</p>
                        <p className="font-bold tabular-nums">{item.value}</p>
                      </div>
                    ))}
                  </div>

                  {/* Accounts table */}
                  <div>
                    <p className="text-[9px] font-bold uppercase tracking-widest border-b border-foreground pb-1 mb-0">Account Overview</p>
                    <table className="w-full border-collapse">
                      <thead>
                        <tr className="bg-muted/60">
                          {["Prop Firm", "Account No.", "Expenses", "Income", "Net"].map((h, i) => (
                            <th key={h} className={`px-2 py-1.5 text-[9px] font-semibold uppercase tracking-wide border-b border-border ${i >= 2 ? "text-right" : "text-left"}`}>{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {accounts.length === 0 ? (
                          <tr><td colSpan={5} className="text-center text-muted-foreground py-3">No accounts recorded</td></tr>
                        ) : (
                          accounts.map((acc) => {
                            const ps = (acc.payoutHistory || []).reduce((s, p) => s + (p.amount || 0), 0);
                            const n = ps - (acc.initialCost || 0);
                            return (
                              <tr key={acc.id} className="border-b border-border/50">
                                <td className="px-2 py-1.5">{acc.propFirm}</td>
                                <td className="px-2 py-1.5">{acc.accountNumber}</td>
                                <td className="px-2 py-1.5 text-right tabular-nums">- {fmtCurrency(acc.initialCost || 0, country)}</td>
                                <td className="px-2 py-1.5 text-right tabular-nums">+ {fmtCurrency(ps, country)}</td>
                                <td className="px-2 py-1.5 text-right font-semibold tabular-nums">{n >= 0 ? "+" : ""}{fmtCurrency(n, country)}</td>
                              </tr>
                            );
                          })
                        )}
                        <tr className="border-t border-foreground font-bold bg-muted/40">
                          <td colSpan={2} className="px-2 py-1.5">Total</td>
                          <td className="px-2 py-1.5 text-right tabular-nums">- {fmtCurrency(totalExpenses, country)}</td>
                          <td className="px-2 py-1.5 text-right tabular-nums">+ {fmtCurrency(totalPayouts, country)}</td>
                          <td className="px-2 py-1.5 text-right tabular-nums">{isProfit ? "+" : ""}{fmtCurrency(netProfit, country)}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  {/* Payout history */}
                  <div>
                    <p className="text-[9px] font-bold uppercase tracking-widest border-b border-foreground pb-1 mb-0">Payout History</p>
                    <table className="w-full border-collapse">
                      <thead>
                        <tr className="bg-muted/60">
                          {["Prop Firm", "Account No.", "Date", "Amount"].map((h, i) => (
                            <th key={h} className={`px-2 py-1.5 text-[9px] font-semibold uppercase tracking-wide border-b border-border ${i === 3 ? "text-right" : "text-left"}`}>{h}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {accounts.every((a) => !a.payoutHistory?.length) ? (
                          <tr><td colSpan={4} className="text-center text-muted-foreground py-3">No payouts recorded</td></tr>
                        ) : (
                          accounts.flatMap((acc) =>
                            (acc.payoutHistory || []).map((p, i) => (
                              <tr key={`${acc.id}-${i}`} className="border-b border-border/50">
                                <td className="px-2 py-1.5">{acc.propFirm}</td>
                                <td className="px-2 py-1.5">{acc.accountNumber}</td>
                                <td className="px-2 py-1.5">{new Date(p.date).toLocaleDateString(country.dateLocale, { year: "numeric", month: "short", day: "numeric" })}</td>
                                <td className="px-2 py-1.5 text-right font-semibold tabular-nums">+ {fmtCurrency(p.amount || 0, country)}</td>
                              </tr>
                            ))
                          )
                        )}
                      </tbody>
                    </table>
                  </div>

                  <div className="text-[8px] text-muted-foreground border-t border-border pt-2 leading-relaxed space-y-1.5">
                    <p className="font-semibold text-foreground not-italic">DISCLAIMER &amp; LIMITATION OF LIABILITY</p>
                    <p>This document was automatically generated by CycleWise solely for informational and organizational purposes. All data was entered manually by the user and has <strong>not been verified, audited, or confirmed</strong> by CycleWise or any affiliated party. <strong>CycleWise expressly disclaims all liability</strong> for any errors, omissions, inaccuracies, or incompleteness of the information presented.</p>
                    <p>This document does <strong>not constitute tax advice, legal advice, or financial advice</strong> of any kind. {country.disclaimer}</p>
                    <p>The user is solely responsible for verifying all figures and for complying with applicable tax laws. CycleWise, its developers, operators, and contributors shall not be held liable for any damages, penalties, or legal consequences arising from the use of or reliance on this document. <strong>Always consult a licensed tax professional</strong> before submitting any tax-related documentation.</p>
                  </div>
                </div>
              </ScrollArea>
            </TabsContent>
          </Tabs>

          {/* Footer with Download Button */}
          <div className="px-6 py-4 border-t border-border bg-muted/30 rounded-b-lg flex-shrink-0">
            <div className="flex items-center justify-between gap-3">
              <p className="text-xs text-muted-foreground">
                Opens in browser – use{" "}
                <kbd className="rounded bg-muted px-1 py-0.5 text-[10px] font-mono">
                  Cmd+P
                </kbd>{" "}
                to save as PDF.
              </p>
              <Button onClick={generateAndPrint} className="gap-2 shrink-0">
                <Printer className="h-4 w-4" />
                Create PDF &amp; Print
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </>
  );
}
